spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 #日期序列化走北京时间
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 7060
#  servlet:
#    context-path: /demo
#    session:
#      cookie:
#        http-only: true
#        secure: true
#      timeout: 30m
#  tomcat: # 以下配置均为tomcat9.x的默认值
#    max-threads: 200
#    min-spare-threads: 10
#    max-connections: 10000
#    accept-count: 100
#SSO
#SSO
#systemId
artery:
  login:
    enabled: true
    ssoServer: http://172.16.34.115:8084/ssoserver
  #当您需要使用组织机构的数据时,需要将您的rootcorpid 设置为您需要的;例如:
  root:
    corp: 0
#uim-api
taap:
  base:
    uimApi:
      url: http://172.16.34.115:6789/uim-api/

# systemid 所在的文件必须为 utf-8 编码
# 集成 sdk 的应用无须对 sysmemid 进行编码，sdk 会自己做
# http 请求头设置
systemid: hfdf
authcode: df5cd38c0ead11e7810db7ce82342409
msg:
  main:
    url: http://172.16.34.115:8087/msg-main
    request:
      timeout: 2000
tas:
  connection-limit:
    limit: 1000
