spring:
  thymeleaf:
    cache: false
  datasource:
    name: dataSource
    url: jdbc:ArteryBase://172.16.34.54:5432/db_clue?currentSchema=db_clue
    username: sa
    password: ENCRYPT#g3J0wPwVx24eVe/lEupktA==
    driver-class-name: com.thunisoft.ArteryBase.Driver